### PR TITLE
Use spdx version 0.9

### PR DESCRIPTION
**Pull request by o0Ignition0o**
### Checklist

* [x] I have read the [Contributor Guide](../CONTRIBUTING.md)
* [x] I have read and agree to the [Code of Conduct](../CODE_OF_CONDUCT.md)
* [x] I have added a description of my changes and why I'd like them included in the section below

### Description of Changes

This PR updates SPDX to version 0.9, which will allow `cargo-about` to run against `Elastic-2.0` licensed crates.

### Related Issues

This is the second step towards fixing https://github.com/apollographql/router/issues/2055

PS: I tried to understand where `spdx_cache.bin.zstd` comes from and how to update it, but I'm not sure.

Happy to update it and add a section to the readme if it can help :)

### CODE REVIEW

**Comment by o0Ignition0o** [comment]
@Jake-Shadle Do you happen to know how to update `spdx_cache.bin.zstd`?

Happy to iterate on the PR if you have an idea :)

**Comment by o0Ignition0o** [comment]
Hey @Jake-Shadle , is there anything I can do to help take it to the finish line? I would love us to use cargo about with elv2!

**Comment by Jake-Shadle** [comment]
Oops, thought this was merged automatically, I'll merge and do a release later today, sorry for the delay.

**Comment by o0Ignition0o** [comment]
No worries at all, thank you for your time 😊

**Review by Jake-Shadle — APPROVED** [review]

**Pull request merged**
